# Generated by Django 2.0.4 on 2018-05-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawler',
            name='cancel_flag',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
