# Generated by Django 2.0.4 on 2018-05-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_crawler_cancel_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler',
            name='cancel_flag',
            field=models.BooleanField(default=False),
        ),
    ]
