# Generated by Django 2.0.4 on 2018-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20180502_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
