# Generated by Django 2.0.4 on 2018-05-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20180503_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler',
            name='status',
            field=models.TextField(),
        ),
    ]
