# Generated by Django 2.0.4 on 2018-05-02 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttrs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='evauations', to='ttrs.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='not_recommends',
            field=models.ManyToManyField(blank=True, to='ttrs.Course'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ttrs.Classroom'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='lectures',
            field=models.ManyToManyField(blank=True, related_name='lectures', to='ttrs.Lecture'),
        ),
    ]
