# Generated by Django 2.0.4 on 2018-05-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttrs', '0002_auto_20180502_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student'},
        ),
    ]
