# Generated by Django 2.0.4 on 2018-05-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttrs', '0003_auto_20180502_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='end',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='start',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day_of_week',
            field=models.CharField(default='00:00', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_time',
            field=models.CharField(default='00:00', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.CharField(default='00:00', max_length=10),
            preserve_default=False,
        ),
    ]
